kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "front-service.fullname" . }}
  labels:
    app: {{ template "front-service.name" . }}
    chart: {{ template "front-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]